### ISSUE TITLE
Decoding error when cookie is encrypted

### ISSUE THREAD

**Issue by svenkubiak** [svenkubiak/mangooio#103]
When cookie encryption is enable the following errors is thrown:

            Exception in thread "XNIO-1 task-24" org.bouncycastle.util.encoders.DecoderException: unable to decode base64 string: invalid characters encountered in base64 data
            at org.bouncycastle.util.encoders.Base64.decode(Unknown Source)
            at io.mangoo.crypto.Crypto.decrypt(Crypto.java:74)
            at io.mangoo.crypto.Crypto.decrypt(Crypto.java:55)
            at io.mangoo.utils.RequestUtils.hasValidAuthentication(RequestUtils.java:185)
            at io.mangoo.routing.handlers.ServerSentEventHandler.connected(ServerSentEventHandler.java:33)
            at io.undertow.server.handlers.sse.ServerSentEventHandler.handleConnect(ServerSentEventHandler.java:93)
            at io.undertow.server.handlers.sse.ServerSentEventHandler.access$000(ServerSentEventHandler.java:38)
            at io.undertow.server.handlers.sse.ServerSentEventHandler$2.run(ServerSentEventHandler.java:71)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)
    Caused by: java.io.IOException: invalid characters encountered in base64 data
            at org.bouncycastle.util.encoders.Base64Encoder.decode(Unknown Source)
            ... 11 more

First investigation suggest, that this happens when cookie encryption is enable and an unencrypted cookie is passed to the decrypt function.

**Comment by MarkVink** [comment]
Please note; this also accursed when I deleted my cookies on forehand. On my experience this behaviour is showen after a few requests when cookie encryption is enabled.

**Comment by svenkubiak** [comment]
Probably found it. setSessionCookie was calling

    if (this.config.isAuthenticationCookieEncrypt()) {
                value = Application.getInstance(Crypto.class).encrypt(value);
            }

which should be

if (this.config.isSessionCookieEncrypt()) {
                value = Application.getInstance(Crypto.class).encrypt(value);
            }
