### ISSUE TITLE
NPE on creation of JSON Object from request parameter

### ISSUE THREAD

**Issue by ismagilov** [svenkubiak/mangooio#290]
While playing with the framework, I follow this development workflow:
1. `mvn clean package`
1. `mvn mangooio:run`
1. Make changes in code
1. Recompile it in IDEA
1. mangooio automatically reloads (it can be seen in console output)
1. Finally, we get all changes applied

Suddenly, I have notices, that when I change controller method signature, the change is not detected. 

When I change this method:
```
   public Response create(Todo r) {
          // Map myjson = r.getBodyAsJsonMap();
          // System.out.println("Title: " + myjson.get("title"));
          System.out.println(r.title);
...
```

... into this one:
```
    public Response create(Request r) {
        Map myjson = r.getBodyAsJsonMap();
        System.out.println("Title: " + myjson.get("title"));
        // System.out.println(r.title);
...
```

Framework is not reloaded (nothing is changed in console). And when requesting this `create(...)` method, I get the old output. As soon as I rerun `mvn mangooio:run`, I see new output.

Is it expected behaviour? Or a bug?

I have heard, that hot-swapping of classes, when only method signature is changed is very tricky. That's why special tools, like JRebel, exist. But I didn't find anything similar to it in a framework. So, how reliable is your hot-swapping of Java classes?

**Comment by svenkubiak** [comment]
You are right, there is no hot-swapping. It is a simple File-Watcher that checks if the compiled file has changed. Or rather if any file has been changed in the target folder. So it should detect *all* code changes.

I could not reproduce the error on Eclipse. Changed method signature and maven runner reloaded as usual. I am no expert in IDEA, but this smells like an IDE issue.

**Comment by ismagilov** [comment]
I have looked into it once again, and probably, found a reason of such behaviour. IDEA works as expected. Class-files are regenerated, their modification time changes, and mangooio reloads an application. 

I had another problem, which probably caused mangooio from reloading the app. 

When I use this version of controller:
```
public Response create(Todo r) {
    System.out.println(r.title);
```

... model class `Todo` is used: 
```
public class Todo {
    public long id;
    @JsonInclude
    public String title;
    public boolean completed;
}
```
... and the framework doesn't create a `Todo` from JSON, `r` is `null`:
```
1.04.2017 12:06:25,791 [XNIO-1 task-1] ERROR io.undertow.request - UT005071: Undertow request failed HttpServerExchange{ POST / request {Accept=[*/*], Connection=[Keep-Alive], Cache-Control=[no-cache], Accept-Encoding=[gzip,deflate], Content-Length=[18], Content-Type=[*/*; charset=UTF-8], User-Agent=[Apache-HttpClient/4.5.2 (Java/1.8.0_112-release)], Host=[localhost:9090]} response {}}
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at io.mangoo.routing.handlers.RequestHandler.invokeController(RequestHandler.java:134) ~[mangooio-core-4.3.2.jar:?]
	at io.mangoo.routing.handlers.RequestHandler.getResponse(RequestHandler.java:111) ~[mangooio-core-4.3.2.jar:?]
	at io.mangoo.routing.handlers.RequestHandler.handleRequest(RequestHandler.java:46) ~[mangooio-core-4.3.2.jar:?]
	at io.mangoo.routing.handlers.FormHandler.nextHandler(FormHandler.java:95) ~[mangooio-core-4.3.2.jar:?]
	at io.mangoo.routing.handlers.FormHandler.handleRequest(FormHandler.java:37) ~[mangooio-core-4.3.2.jar:?]
	at io.mangoo.routing.handlers.InboundCookiesHandler.nextHandler(InboundCookiesHandler.java:165) ~[mangooio-core-4.3.2.jar:?]
	at io.mangoo.routing.handlers.InboundCookiesHandler.handleRequest(InboundCookiesHandler.java:62) ~[mangooio-core-4.3.2.jar:?]
	at io.mangoo.routing.handlers.LocaleHandler.nextHandler(LocaleHandler.java:69) ~[mangooio-core-4.3.2.jar:?]
	at io.mangoo.routing.handlers.LocaleHandler.handleRequest(LocaleHandler.java:58) ~[mangooio-core-4.3.2.jar:?]
	at io.mangoo.routing.handlers.LimitHandler.nextHandler(LimitHandler.java:92) ~[mangooio-core-4.3.2.jar:?]
	at io.mangoo.routing.handlers.LimitHandler.handleRequest(LimitHandler.java:47) ~[mangooio-core-4.3.2.jar:?]
	at io.mangoo.routing.handlers.DispatcherHandler.nextHandler(DispatcherHandler.java:199) ~[mangooio-core-4.3.2.jar:?]
	at io.mangoo.routing.handlers.DispatcherHandler.handleRequest(DispatcherHandler.java:171) ~[mangooio-core-4.3.2.jar:?]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211) [undertow-core-1.4.11.Final.jar:1.4.11.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [undertow-core-1.4.11.Final.jar:1.4.11.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at controllers.ApplicationController.create(ApplicationController.java:32) ~[classes/:?]
	... 22 more
```

As soon as I get the exception, reloading stops working.

Routes:
```
- method: POST
  url: /
  mapping: ApplicationController.create
```

POST request:
```
{"title":"a todo"}
```

So, to reproduce the issue you should break creation of a parameter object from JSON.

**Comment by svenkubiak** [comment]
Yes. I can reproduce the bug and have changed topic accordingly.

**Comment by svenkubiak** [comment]
Just to narrow down the error, as we have a working unit test on this, did you set Content-Type = application/json? Can you also check if it works when you create getters and setters in your class. Thanks.

**Comment by ismagilov** [comment]
The header was not set when I reported a bug. Now after adding `Content-Type = application/json` it started working:
```
    public Response create(Todo t) {
        System.out.println(t);
        System.out.println(t.title);

        return Response.withOk().andEmptyBody();
    }
```

```
11.04.2017 16:26:44,927 [main] INFO  io.mangoo.core.Bootstrap - mangoo I/O application started in 1929 ms in dev mode. Enjoy.
model.Todo@71d2496b
a todo
```

**Comment by svenkubiak** [comment]
Happy to help 😄
