### ISSUE TITLE
NPE when css files are modified

### ISSUE THREAD

**Issue by ezcamlive** [svenkubiak/mangooio#80]
I am running locally using mangooio:run and when I make changes to css file minification task throws a null pointer exception and I have to start the server again.

I edit the files using sublime text and keep eclipse in the background and refresh in eclipse to build the project.

**Comment by svenkubiak** [comment]
Which version are you on? Have you enabled on-the-fly minification?

Cheers,
Sven

**Comment by ezcamlive** [comment]
1.1.3 is the version.
I have not done anything to enable on-the-fly minification? Where should I look for that?

**Comment by ezcamlive** [comment]
minify:
            js        : false
            css       : false
            jsfolder  : /assets/javascript
            cssfolder : /assets/css
            gzipjs    : false
            gzipcss   : false

**Comment by svenkubiak** [comment]
I remeber fixing an NPE in the plugin. Could you try the latest version or at least 1.2.0?

Cheers,
Sven

**Comment by svenkubiak** [comment]
I found the bug and can reproduce the NPE. Working on a fix.

Cheers,
Sven

**Comment by svenkubiak** [comment]
I just release version 1.1.4.1 and 1.3.2, which both contain a patch. Could you check and confirm that it is fixed? Also please note, as this was a very minor path I also patched the 1.1.x version, but 1.1.x won't be maintained in the future. Specially when 2.0.0 comes out, the 1.3.x branch will go in maintenance.

**Comment by ezcamlive** [comment]
Thanks. I don't get NPE now after switching to 1.3.2.

However JVM crashes with

1) No implementation for io.mangoo.interfaces.MangooLifecycle was bound.
  while locating io.mangoo.interfaces.MangooLifecycle

**Comment by svenkubiak** [comment]
When dies this error occur? Can you try a mvn clean package?

**Comment by ezcamlive** [comment]
I did run mvn clean package.

I keep eclipse in the background and run 
mvn clean package
mvn mangooio:run
Then I go to eclipse and hit F5 and project gets built
Now I get the error

**Comment by ezcamlive** [comment]
21.11.2015;11:27:11.930 [main] ERROR io.mangoo.core.Bootstrap - Failed to load m
odules. Check that conf/Module.java exisits in your application
java.lang.ClassNotFoundException: conf.Module
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[na:1.8.0_25]

        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.8.0_25]

        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0
_25]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[na:1.8.0
_25]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_25]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.
8.0_25]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_25]
        at java.lang.Class.forName0(Native Method) ~[na:1.8.0_25]
        at java.lang.Class.forName(Class.java:260) ~[na:1.8.0_25]
        at io.mangoo.core.Bootstrap.getModules(Bootstrap.java:220) [mangooio-cor
e-1.3.2.jar:na]
        at io.mangoo.core.Bootstrap.prepareInjector(Bootstrap.java:104) [mangooi
o-core-1.3.2.jar:na]
        at io.mangoo.core.Application.main(Application.java:26) [mangooio-core-1
.3.2.jar:na]
Exception in thread "main" com.google.inject.ConfigurationException: Guice confi
guration errors:

1) No implementation for io.mangoo.interfaces.MangooLifecycle was bound.
  while locating io.mangoo.interfaces.MangooLifecycle

1 error
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java
:1042)
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java
:1001)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java
:1051)
        at io.mangoo.core.Bootstrap.applicationInitialized(Bootstrap.java:109)
        at io.mangoo.core.Application.main(Application.java:27)
[ERROR] JVM process terminated (next file change will attempt to restart it)

**Comment by svenkubiak** [comment]
Does the conf/Module.java class exist in your project?

**Comment by ezcamlive** [comment]
yes.

On Sat, Nov 21, 2015 at 11:31 AM, Sven Kubiak <notifications@github.com>
wrote:

> Does the conf/Module.java class exist in your project?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/svenkubiak/mangooio/issues/80#issuecomment-158660564>.
>



-- 
Thanks,
EzCamLive Support

**Comment by ezcamlive** [comment]
But if run mvn package again and run it, it works.

**Comment by svenkubiak** [comment]
Ok. I will add this to the docs. Can I close the issue?

**Comment by ezcamlive** [comment]
Yes. Please close it. I will post back if I find a better workflow.
